baseURL = "https://jonjomckay.com/blog/"
languageCode = "en-us"
title = "Jonjo McKay"
theme = "hello-friend"
disqusShortname = "jonjomckay"
canonifyURLs = "true"

[params]
defaultTheme = "light"

[permalinks]
posts = "/:year/:month/:title/"

[languages]
    [languages.en]
        title = "Jonjo McKay"

        [languages.en.params.logo]
        logoText = "jonjomckay"